//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociationRegistry.Admin.Api {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssociationRegistry.Admin.Api.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging werd niet gevonden..
        /// </summary>
        public static string Status404Detail {
            get {
                return ResourceManager.GetString("Status404Detail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De historiek van de gevraagde vereniging is niet gevonden..
        /// </summary>
        public static string Status404Historiek {
            get {
                return ResourceManager.GetString("Status404Historiek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging werd niet gevonden..
        /// </summary>
        public static string Status404NotFound {
            get {
                return ResourceManager.GetString("Status404NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Er zijn één of meerdere mogelijke duplicaten van deze vereniging gevonden..
        /// </summary>
        public static string Status409RegistratieAfdeling {
            get {
                return ResourceManager.GetString("Status409RegistratieAfdeling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Er zijn één of meerdere mogelijke duplicaten van deze vereniging gevonden..
        /// </summary>
        public static string Status409RegistratieFeitelijkeVereniging {
            get {
                return ResourceManager.GetString("Status409RegistratieFeitelijkeVereniging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Het detail van de gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412Detail {
            get {
                return ResourceManager.GetString("Status412Detail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De historiek van de gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412Historiek {
            get {
                return ResourceManager.GetString("Status412Historiek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412PreconditionFailed {
            get {
                return ResourceManager.GetString("Status412PreconditionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412Stop {
            get {
                return ResourceManager.GetString("Status412Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412VerwijderContactGegeven {
            get {
                return ResourceManager.GetString("Status412VerwijderContactGegeven", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412VerwijderLocatie {
            get {
                return ResourceManager.GetString("Status412VerwijderLocatie", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412VerwijderVertegenwoordiger {
            get {
                return ResourceManager.GetString("Status412VerwijderVertegenwoordiger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412VoegContactGegevenToe {
            get {
                return ResourceManager.GetString("Status412VoegContactGegevenToe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412VoegLocatieToe {
            get {
                return ResourceManager.GetString("Status412VoegLocatieToe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412VoegVertegenwoordigerToe {
            get {
                return ResourceManager.GetString("Status412VoegVertegenwoordigerToe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412WijzigContactGegeven {
            get {
                return ResourceManager.GetString("Status412WijzigContactGegeven", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412WijzigKboBasisgegevens {
            get {
                return ResourceManager.GetString("Status412WijzigKboBasisgegevens", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412WijzigKboContactgegevens {
            get {
                return ResourceManager.GetString("Status412WijzigKboContactgegevens", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412WijzigKboMaatschappelijkeZetel {
            get {
                return ResourceManager.GetString("Status412WijzigKboMaatschappelijkeZetel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412WijzigLocatie {
            get {
                return ResourceManager.GetString("Status412WijzigLocatie", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412WijzigVertegenwoordiger {
            get {
                return ResourceManager.GetString("Status412WijzigVertegenwoordiger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De gevraagde vereniging heeft niet de verwachte sequentiewaarde..
        /// </summary>
        public static string Status412Zoek {
            get {
                return ResourceManager.GetString("Status412Zoek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is verplicht..
        /// </summary>
        public static string VeldIsVerplicht {
            get {
                return ResourceManager.GetString("VeldIsVerplicht", resourceCulture);
            }
        }
    }
}
