//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociationRegistry.Admin.Api {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class ValidationMessages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (Equals(null, resourceMan)) {
                    ResourceManager temp = new ResourceManager("AssociationRegistry.Admin.Api.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string VeldIsVerplicht {
            get {
                return ResourceManager.GetString("VeldIsVerplicht", resourceCulture);
            }
        }
        
        public static string Status404Detail {
            get {
                return ResourceManager.GetString("Status404Detail", resourceCulture);
            }
        }
        
        public static string Status404Deleted {
            get {
                return ResourceManager.GetString("Status404Deleted", resourceCulture);
            }
        }
        
        public static string Status412Detail {
            get {
                return ResourceManager.GetString("Status412Detail", resourceCulture);
            }
        }
        
        public static string Status404Historiek {
            get {
                return ResourceManager.GetString("Status404Historiek", resourceCulture);
            }
        }
        
        public static string Status412Historiek {
            get {
                return ResourceManager.GetString("Status412Historiek", resourceCulture);
            }
        }
        
        public static string Status409RegistratieFeitelijkeVereniging {
            get {
                return ResourceManager.GetString("Status409RegistratieFeitelijkeVereniging", resourceCulture);
            }
        }
        
        public static string Status412PreconditionFailed {
            get {
                return ResourceManager.GetString("Status412PreconditionFailed", resourceCulture);
            }
        }
        
        public static string Status404NotFound {
            get {
                return ResourceManager.GetString("Status404NotFound", resourceCulture);
            }
        }
    }
}
