services:

  admin-migrations:
    build:
      context: migrations/admin.api/
      dockerfile: Dockerfile
      args:
        CI_BUILD_NUMBER: "8.2.3"
        GIT_HASH: "local-dev"
    container_name: vr_admin_migrations
    environment:
      - APP_CONNSTRING=Host=db;Port=5432;Database=verenigingsregister;Username=root;Password=root;
      - DATABASE_TYPE=postgresql
    depends_on:
      - db
    networks:
      - vr-net

  admin-api:
    restart: on-failure
    build:
      context: .
      dockerfile: src/AssociationRegistry.Admin.Api/Dockerfile

    container_name: vr_admin_api
    ports:
      - "11004:11004"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ElasticClientOptions__Uri: "http://elasticsearch:9200"
      ElasticClientOptions__Username: "elastic"
      ElasticClientOptions__Password: "local_development"
      ElasticClientOptions__Indices__Verenigingen: "verenigingsregister-verenigingen-admin"
      ElasticClientOptions__Indices__DuplicateDetection: "verenigingsregister-duplicate-detection"
      ElasticClientOptions__EnableDevelopmentLogs: true

      PostgreSQLOptions__Host: "db"
      PostgreSQLOptions__database: "verenigingsregister"
      PostgreSQLOptions__username: "root"
      PostgreSQLOptions__password: "root"

      COLLECTOR_URL: "http://otel-collector:4317"

      OAuth2IntrospectionOptions__Authority: "http://acm"
      OAuth2IntrospectionOptions__IntrospectionEndpoint: "http://acm/connect/introspect"

      OAuth2IntrospectionOptions__ClientId: "association-registry-local-dev-admin"
      OAuth2IntrospectionOptions__ClientSecret: "a_very=Secr3t*Key"

      GrarOptions__Sqs__GrarSyncQueueUrl: "https://localstack:4566/000000000000/grar-sync"
      GrarOptions__Sqs__UseLocalStack: "true"

      GrarOptions__Wolverine__TransportServiceUrl: "http://localstack:4566"
      GrarOptions__HttpClient__BaseUrl: "http://wiremock:8080"
      MagdaOptions__GeefOndernemingVkboEndpoint: "http://wiremock:8080/GeefOndernemingVkboDienst-02.00/soap/WebService"
      MagdaOptions__GeefOndernemingEndpoint: "http://wiremock:8080/GeefOndernemingDienst-02.00/soap/WebService"
      MagdaOptions__RegistreerInschrijvingEndpoint: "http://wiremock:8080/RegistreerInschrijvingDienst-02.01/soap/WebService"

      LiveMagdaOptions__GeefOndernemingVkboEndpoint: "http://wiremock:8080/GeefOndernemingVkboDienst-02.00/soap/WebService"
      LiveMagdaOptions__GeefOndernemingEndpoint: "http://wiremock:8080/GeefOndernemingDienst-02.00/soap/WebService"
      LiveMagdaOptions__RegistreerInschrijvingEndpoint: "http://wiremock:8080/RegistreerInschrijvingDienst-02.01/soap/WebService"
      SuperAdminClientIds: "vloketClient,superAdminClient"
    depends_on:
      admin-migrations:
        condition: service_completed_successfully
      db:
        condition: service_started
      elasticsearch:
        condition: service_started
      acm:
        condition: service_started
      localstack:
        condition: service_started
      wiremock:
        condition: service_started
    networks:
      - vr-net

  token-fetcher:
    image: curlimages/curl
    command: >
      -X POST "http://acm/connect/token"
      -u "superAdminClient:secret"
      -H "Content-Type: application/x-www-form-urlencoded"
      -d "grant_type=client_credentials&scope=vo_info dv_verenigingsregister_beheer"
    depends_on:
      - acm
    networks:
      - vr-net

  admin-projections:
    restart: on-failure
    build:
      context: .
      dockerfile: src/AssociationRegistry.Admin.ProjectionHost/Dockerfile

    container_name: vr_admin_projections
    ports:
      - "11006:11006"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ElasticClientOptions__Uri: "http://elasticsearch:9200"
      ElasticClientOptions__Username: "elastic"
      ElasticClientOptions__Password: "local_development"
      ElasticClientOptions__Indices__Verenigingen: "verenigingsregister-verenigingen-admin"
      ElasticClientOptions__Indices__DuplicateDetection: "verenigingsregister-duplicate-detection"
      ElasticClientOptions__EnableDevelopmentLogs: true

      COLLECTOR_URL: "http://otel-collector:4317"

      PostgreSQLOptions__Host: "db"
      PostgreSQLOptions__database: "verenigingsregister"
      PostgreSQLOptions__username: "root"
      PostgreSQLOptions__password: "root"

      OAuth2IntrospectionOptions__Authority: "http://acm"
      OAuth2IntrospectionOptions__IntrospectionEndpoint: "http://acm/connect/introspect"

    depends_on:
      - db
      - elasticsearch
      - acm
      - localstack
      - wiremock
    networks:
      - vr-net
networks:
  vr-net:
