GRANT CONNECT ON DATABASE verenigingsregister TO fullaccess;
GRANT USAGE ON SCHEMA public TO fullaccess;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fullaccess;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fullaccess;
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO fullaccess;