namespace AssociationRegistry.CommandHandling.DecentraalBeheer.Acties.Registratie.RegistreerVerenigingUitKbo;

using AssociationRegistry.DecentraalBeheer.Vereniging;

public record RegistreerVerenigingUitKboCommand(KboNummer KboNummer);
