namespace AssociationRegistry.Acties.RegistreerFeitelijkeVereniging;

using AssociationRegistry.DuplicateVerenigingDetection;

public record PotentialDuplicatesFound(IEnumerable<DuplicaatVereniging> Candidates);
