namespace AssociationRegistry.CommandHandling.Bewaartermijnen.MessageHandlers.Vertegenwoordigers.VertegenwoordigerWerdVerwijderd;

public class StartBewaartermijnVoorVerwijderVertegenwoordigerMessageHandler
{

}
