//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociationRegistry.Magda.Onderneming.GeefOndernemingVKBO
{
    using System.CodeDom.Compiler;
    using System.Diagnostics;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    using System.ServiceModel.Description;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;

    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [ServiceContract(Name="Onderneming.GeefOndernemingVKBOPortType", Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                                                                               "n.be", ConfigurationName="AssociationRegistry.Magda.Onderneming.GeefOndernemingVKBO.OndernemingGeefOndernem" +
                         "ingVKBOPortType")]
    public interface OndernemingGeefOndernemingVKBOPortType
    {
        
        [OperationContract(Action="http://magdaondernemingdienst-intern-aip.vonet.be/GeefOndernemingVKBODienst-02.00" +
                                  "/soap/WebService", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
        Task<GeefOndernemingVKBOResponse1> GeefOndernemingVKBOAsync(GeefOndernemingVKBORequest request);
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(AnonymousType=true, Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                                           "n.be")]
    public partial class GeefOndernemingVKBO
    {
        
        private VerzoekType verzoekField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public VerzoekType Verzoek
        {
            get
            {
                return this.verzoekField;
            }
            set
            {
                this.verzoekField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class VerzoekType
    {
        
        private ContextType contextField;
        
        private VragenType vragenField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public ContextType Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public VragenType Vragen
        {
            get
            {
                return this.vragenField;
            }
            set
            {
                this.vragenField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class ContextType
    {
        
        private string naamField;
        
        private string versieField;
        
        private BerichtType berichtField;
        
        private AnnotatieType[] annotatiesField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Versie
        {
            get
            {
                return this.versieField;
            }
            set
            {
                this.versieField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public BerichtType Bericht
        {
            get
            {
                return this.berichtField;
            }
            set
            {
                this.berichtField = value;
            }
        }
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=3)]
        [XmlArrayItem("Annotatie", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public AnnotatieType[] Annotaties
        {
            get
            {
                return this.annotatiesField;
            }
            set
            {
                this.annotatiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class BerichtType
    {
        
        private BerichtTypeType typeField;
        
        private TijdstipType tijdstipField;
        
        private AfzenderAdresType afzenderField;
        
        private OntvangerAdresType ontvangerField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public BerichtTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public TijdstipType Tijdstip
        {
            get
            {
                return this.tijdstipField;
            }
            set
            {
                this.tijdstipField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public AfzenderAdresType Afzender
        {
            get
            {
                return this.afzenderField;
            }
            set
            {
                this.afzenderField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public OntvangerAdresType Ontvanger
        {
            get
            {
                return this.ontvangerField;
            }
            set
            {
                this.ontvangerField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public enum BerichtTypeType
    {
        
        /// <remarks/>
        VRAAG,
        
        /// <remarks/>
        ANTWOORD,
        
        /// <remarks/>
        VOORLOPIG_ANTWOORD,
        
        /// <remarks/>
        DATAGRAM,
        
        /// <remarks/>
        BEVESTIGING,
        
        /// <remarks/>
        UITZONDERING,
        
        /// <remarks/>
        PUBLICATIE,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class TijdstipType
    {
        
        private string datumField;
        
        private string tijdField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Tijd
        {
            get
            {
                return this.tijdField;
            }
            set
            {
                this.tijdField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class UitzonderingType
    {
        
        private string identificatieField;
        
        private string oorsprongField;
        
        private UitzonderingTypeType typeField;
        
        private TijdstipType tijdstipField;
        
        private string diagnoseField;
        
        private string omstandigheidField;
        
        private AnnotatieType[] annotatiesField;
        
        private string[] elementReferentiesField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Identificatie
        {
            get
            {
                return this.identificatieField;
            }
            set
            {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Oorsprong
        {
            get
            {
                return this.oorsprongField;
            }
            set
            {
                this.oorsprongField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public UitzonderingTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public TijdstipType Tijdstip
        {
            get
            {
                return this.tijdstipField;
            }
            set
            {
                this.tijdstipField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public string Diagnose
        {
            get
            {
                return this.diagnoseField;
            }
            set
            {
                this.diagnoseField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public string Omstandigheid
        {
            get
            {
                return this.omstandigheidField;
            }
            set
            {
                this.omstandigheidField = value;
            }
        }
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=6)]
        [XmlArrayItem("Annotatie", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public AnnotatieType[] Annotaties
        {
            get
            {
                return this.annotatiesField;
            }
            set
            {
                this.annotatiesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=7)]
        [XmlArrayItem("ElementReferentie", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ElementReferenties
        {
            get
            {
                return this.elementReferentiesField;
            }
            set
            {
                this.elementReferentiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public enum UitzonderingTypeType
    {
        
        /// <remarks/>
        FOUT,
        
        /// <remarks/>
        WAARSCHUWING,
        
        /// <remarks/>
        INFORMATIE,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class AnnotatieType
    {
        
        private string naamField;
        
        private string waardeField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Waarde
        {
            get
            {
                return this.waardeField;
            }
            set
            {
                this.waardeField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeStopzettingVKBORedenType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class StopzettingVKBORedenType
    {
        
        private CodeStopzettingVKBORedenType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeStopzettingVKBORedenType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class OmschrijvingAlgemeenType
    {
        
        private string oorsprongField;
        
        private string taalCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Oorsprong
        {
            get
            {
                return this.oorsprongField;
            }
            set
            {
                this.oorsprongField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string TaalCode
        {
            get
            {
                return this.taalCodeField;
            }
            set
            {
                this.taalCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class StopzettingVKBOType
    {
        
        private string datumField;
        
        private StopzettingVKBORedenType redenField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public StopzettingVKBORedenType Reden
        {
            get
            {
                return this.redenField;
            }
            set
            {
                this.redenField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class PeriodeVerplichtBeginType
    {
        
        private string beginField;
        
        private string eindeField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Einde
        {
            get
            {
                return this.eindeField;
            }
            set
            {
                this.eindeField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeAmbtshalveDoorhalingTypeRedenType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class AmbtshalveDoorhalingTypeRedenType
    {
        
        private CodeAmbtshalveDoorhalingTypeRedenType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeAmbtshalveDoorhalingTypeRedenType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class AmbtshalveDoorhalingType
    {
        
        private AmbtshalveDoorhalingTypeRedenType redenField;
        
        private PeriodeVerplichtBeginType periodeField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public AmbtshalveDoorhalingTypeRedenType Reden
        {
            get
            {
                return this.redenField;
            }
            set
            {
                this.redenField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public PeriodeVerplichtBeginType Periode
        {
            get
            {
                return this.periodeField;
            }
            set
            {
                this.periodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class RechtstoestandCACVKBOType
    {
        
        private CodeRechtstoestandVKBOType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeRechtstoestandVKBOType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeRechtstoestandVKBOType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeRechtsvormVKBOType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class RechtsvormVKBOType
    {
        
        private CodeRechtsvormVKBOType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeRechtsvormVKBOType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class RechtstoestandVKBOType
    {
        
        private CodeRechtstoestandVKBOType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeRechtstoestandVKBOType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class ContactType
    {
        
        private string telefoonnummerField;
        
        private string faxnummerField;
        
        private string gSMField;
        
        private string emailField;
        
        private string websiteField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Telefoonnummer
        {
            get
            {
                return this.telefoonnummerField;
            }
            set
            {
                this.telefoonnummerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Faxnummer
        {
            get
            {
                return this.faxnummerField;
            }
            set
            {
                this.faxnummerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string GSM
        {
            get
            {
                return this.gSMField;
            }
            set
            {
                this.gSMField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public string Website
        {
            get
            {
                return this.websiteField;
            }
            set
            {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeAdresDoorhalingRedenType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class AdresDoorhalingRedenType
    {
        
        private CodeAdresDoorhalingRedenType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeAdresDoorhalingRedenType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class AdresDoorhalingType
    {
        
        private AdresDoorhalingRedenType redenField;
        
        private string datumField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public AdresDoorhalingRedenType Reden
        {
            get
            {
                return this.redenField;
            }
            set
            {
                this.redenField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class AanvullingenType
    {
        
        private string staatField;
        
        private string tekstField;
        
        private string taalCodeField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Staat
        {
            get
            {
                return this.staatField;
            }
            set
            {
                this.staatField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Tekst
        {
            get
            {
                return this.tekstField;
            }
            set
            {
                this.tekstField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string TaalCode
        {
            get
            {
                return this.taalCodeField;
            }
            set
            {
                this.taalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class Land2_0OptioneelType
    {
        
        private string nISCodeField;
        
        private string iSOCodeField;
        
        private string naamField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string NISCode
        {
            get
            {
                return this.nISCodeField;
            }
            set
            {
                this.nISCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string ISOCode
        {
            get
            {
                return this.iSOCodeField;
            }
            set
            {
                this.iSOCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class GemeenteOptioneel2_0Type
    {
        
        private string nISCodeField;
        
        private string postCodeField;
        
        private string naamField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string NISCode
        {
            get
            {
                return this.nISCodeField;
            }
            set
            {
                this.nISCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class StraatRR2_0Type
    {
        
        private string codeField;
        
        private string naamField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class OndernemingVKBOAdresType
    {
        
        private StraatRR2_0Type straatField;
        
        private string huisnummerField;
        
        private string busnummerField;
        
        private GemeenteOptioneel2_0Type gemeenteField;
        
        private Land2_0OptioneelType landField;
        
        private AanvullingenType aanvullingenField;
        
        private AdresDoorhalingType doorhalingField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public StraatRR2_0Type Straat
        {
            get
            {
                return this.straatField;
            }
            set
            {
                this.straatField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Huisnummer
        {
            get
            {
                return this.huisnummerField;
            }
            set
            {
                this.huisnummerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string Busnummer
        {
            get
            {
                return this.busnummerField;
            }
            set
            {
                this.busnummerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public GemeenteOptioneel2_0Type Gemeente
        {
            get
            {
                return this.gemeenteField;
            }
            set
            {
                this.gemeenteField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public Land2_0OptioneelType Land
        {
            get
            {
                return this.landField;
            }
            set
            {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public AanvullingenType Aanvullingen
        {
            get
            {
                return this.aanvullingenField;
            }
            set
            {
                this.aanvullingenField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=6)]
        public AdresDoorhalingType Doorhaling
        {
            get
            {
                return this.doorhalingField;
            }
            set
            {
                this.doorhalingField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class OndernemingNaamType
    {
        
        private string taalCodeField;
        
        private string datumModificatieField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string TaalCode
        {
            get
            {
                return this.taalCodeField;
            }
            set
            {
                this.taalCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class OndernemingNamenType
    {
        
        private OndernemingNaamType maatschappelijkeNaamField;
        
        private OndernemingNaamType afgekorteNaamField;
        
        private OndernemingNaamType commercieleNaamField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public OndernemingNaamType MaatschappelijkeNaam
        {
            get
            {
                return this.maatschappelijkeNaamField;
            }
            set
            {
                this.maatschappelijkeNaamField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OndernemingNaamType AfgekorteNaam
        {
            get
            {
                return this.afgekorteNaamField;
            }
            set
            {
                this.afgekorteNaamField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public OndernemingNaamType CommercieleNaam
        {
            get
            {
                return this.commercieleNaamField;
            }
            set
            {
                this.commercieleNaamField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class MaatschappelijkeZetelMetDatumType
    {
        
        private string datumModificatieField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeSoortOndernemingType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class SoortOndernemingType
    {
        
        private CodeSoortOndernemingType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeSoortOndernemingType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeStatusKBOType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class StatusKBOType
    {
        
        private CodeStatusKBOType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeStatusKBOType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeOndernemingOfVestigingVKBOType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class OndernemingOfVestigingVKBOType
    {
        
        private CodeOndernemingOfVestigingVKBOType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeOndernemingOfVestigingVKBOType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class CodeAuthentiekeBronType
    {
        
        private string beschrijvingField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class AuthentiekeBronType
    {
        
        private CodeAuthentiekeBronType codeField;
        
        private OmschrijvingAlgemeenType omschrijvingField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public CodeAuthentiekeBronType Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public OmschrijvingAlgemeenType Omschrijving
        {
            get
            {
                return this.omschrijvingField;
            }
            set
            {
                this.omschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://onderneming-02_00.vip.vlaanderen.be")]
    public partial class OndernemingVKBOType
    {
        
        private string ondernemingsnummerField;
        
        private AuthentiekeBronType authentiekeBronField;
        
        private OndernemingOfVestigingVKBOType ondernemingOfVestigingField;
        
        private StatusKBOType statusKBOField;
        
        private SoortOndernemingType soortOndernemingField;
        
        private MaatschappelijkeZetelMetDatumType maatschappelijkeZetelField;
        
        private OndernemingNamenType namenField;
        
        private OndernemingVKBOAdresType adresField;
        
        private ContactType contactField;
        
        private string datumStartField;
        
        private string datumInschrijvingField;
        
        private string datumAfsluitingField;
        
        private RechtstoestandVKBOType rechtstoestandField;
        
        private RechtsvormVKBOType rechtsvormField;
        
        private RechtstoestandCACVKBOType rechtsvormCACField;
        
        private AmbtshalveDoorhalingType ambtshalveDoorhalingField;
        
        private StopzettingVKBOType stopzettingField;
        
        private string datumModificatieField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Ondernemingsnummer
        {
            get
            {
                return this.ondernemingsnummerField;
            }
            set
            {
                this.ondernemingsnummerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public AuthentiekeBronType AuthentiekeBron
        {
            get
            {
                return this.authentiekeBronField;
            }
            set
            {
                this.authentiekeBronField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public OndernemingOfVestigingVKBOType OndernemingOfVestiging
        {
            get
            {
                return this.ondernemingOfVestigingField;
            }
            set
            {
                this.ondernemingOfVestigingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public StatusKBOType StatusKBO
        {
            get
            {
                return this.statusKBOField;
            }
            set
            {
                this.statusKBOField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public SoortOndernemingType SoortOnderneming
        {
            get
            {
                return this.soortOndernemingField;
            }
            set
            {
                this.soortOndernemingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public MaatschappelijkeZetelMetDatumType MaatschappelijkeZetel
        {
            get
            {
                return this.maatschappelijkeZetelField;
            }
            set
            {
                this.maatschappelijkeZetelField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=6)]
        public OndernemingNamenType Namen
        {
            get
            {
                return this.namenField;
            }
            set
            {
                this.namenField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=7)]
        public OndernemingVKBOAdresType Adres
        {
            get
            {
                return this.adresField;
            }
            set
            {
                this.adresField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=8)]
        public ContactType Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=9)]
        public string DatumStart
        {
            get
            {
                return this.datumStartField;
            }
            set
            {
                this.datumStartField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=10)]
        public string DatumInschrijving
        {
            get
            {
                return this.datumInschrijvingField;
            }
            set
            {
                this.datumInschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=11)]
        public string DatumAfsluiting
        {
            get
            {
                return this.datumAfsluitingField;
            }
            set
            {
                this.datumAfsluitingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=12)]
        public RechtstoestandVKBOType Rechtstoestand
        {
            get
            {
                return this.rechtstoestandField;
            }
            set
            {
                this.rechtstoestandField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=13)]
        public RechtsvormVKBOType Rechtsvorm
        {
            get
            {
                return this.rechtsvormField;
            }
            set
            {
                this.rechtsvormField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=14)]
        public RechtstoestandCACVKBOType RechtsvormCAC
        {
            get
            {
                return this.rechtsvormCACField;
            }
            set
            {
                this.rechtsvormCACField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=15)]
        public AmbtshalveDoorhalingType AmbtshalveDoorhaling
        {
            get
            {
                return this.ambtshalveDoorhalingField;
            }
            set
            {
                this.ambtshalveDoorhalingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=16)]
        public StopzettingVKBOType Stopzetting
        {
            get
            {
                return this.stopzettingField;
            }
            set
            {
                this.stopzettingField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DatumModificatie
        {
            get
            {
                return this.datumModificatieField;
            }
            set
            {
                this.datumModificatieField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class AntwoordInhoudType
    {
        
        private OndernemingVKBOType ondernemingField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public OndernemingVKBOType Onderneming
        {
            get
            {
                return this.ondernemingField;
            }
            set
            {
                this.ondernemingField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class AntwoordType
    {
        
        private string referteField;
        
        private AntwoordInhoudType inhoudField;
        
        private UitzonderingType[] uitzonderingenField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public AntwoordInhoudType Inhoud
        {
            get
            {
                return this.inhoudField;
            }
            set
            {
                this.inhoudField = value;
            }
        }
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=2)]
        [XmlArrayItem("Uitzondering", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public UitzonderingType[] Uitzonderingen
        {
            get
            {
                return this.uitzonderingenField;
            }
            set
            {
                this.uitzonderingenField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class AntwoordenType
    {
        
        private AntwoordType antwoordField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public AntwoordType Antwoord
        {
            get
            {
                return this.antwoordField;
            }
            set
            {
                this.antwoordField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class RepliekType
    {
        
        private ContextType contextField;
        
        private AntwoordenType antwoordenField;
        
        private UitzonderingType[] uitzonderingenField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public ContextType Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public AntwoordenType Antwoorden
        {
            get
            {
                return this.antwoordenField;
            }
            set
            {
                this.antwoordenField = value;
            }
        }
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=2)]
        [XmlArrayItem("Uitzondering", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public UitzonderingType[] Uitzonderingen
        {
            get
            {
                return this.uitzonderingenField;
            }
            set
            {
                this.uitzonderingenField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class VraagInhoudType
    {
        
        private string ondernemingsnummerField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Ondernemingsnummer
        {
            get
            {
                return this.ondernemingsnummerField;
            }
            set
            {
                this.ondernemingsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class VraagType
    {
        
        private string referteField;
        
        private VraagInhoudType inhoudField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public VraagInhoudType Inhoud
        {
            get
            {
                return this.inhoudField;
            }
            set
            {
                this.inhoudField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                       "n.be")]
    public partial class VragenType
    {
        
        private VraagType vraagField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public VraagType Vraag
        {
            get
            {
                return this.vraagField;
            }
            set
            {
                this.vraagField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class OntvangerAdresType
    {
        
        private string identificatieField;
        
        private string naamField;
        
        private string referteField;
        
        private string organisatieEenheidField;
        
        private string hoedanigheidField;
        
        private string gebruikerField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Identificatie
        {
            get
            {
                return this.identificatieField;
            }
            set
            {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string OrganisatieEenheid
        {
            get
            {
                return this.organisatieEenheidField;
            }
            set
            {
                this.organisatieEenheidField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public string Hoedanigheid
        {
            get
            {
                return this.hoedanigheidField;
            }
            set
            {
                this.hoedanigheidField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public string Gebruiker
        {
            get
            {
                return this.gebruikerField;
            }
            set
            {
                this.gebruikerField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class AfzenderAdresType
    {
        
        private string identificatieField;
        
        private string naamField;
        
        private string referteField;
        
        private string organisatieEenheidField;
        
        private string hoedanigheidField;
        
        private string gebruikerField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Identificatie
        {
            get
            {
                return this.identificatieField;
            }
            set
            {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string OrganisatieEenheid
        {
            get
            {
                return this.organisatieEenheidField;
            }
            set
            {
                this.organisatieEenheidField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public string Hoedanigheid
        {
            get
            {
                return this.hoedanigheidField;
            }
            set
            {
                this.hoedanigheidField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public string Gebruiker
        {
            get
            {
                return this.gebruikerField;
            }
            set
            {
                this.gebruikerField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(AnonymousType=true, Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                                           "n.be")]
    public partial class GeefOndernemingVKBOResponse
    {
        
        private RepliekType repliekField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public RepliekType Repliek
        {
            get
            {
                return this.repliekField;
            }
            set
            {
                this.repliekField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [MessageContract(IsWrapped=false)]
    public partial class GeefOndernemingVKBORequest
    {
        
        [MessageBodyMember(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                                     "n.be", Order=0)]
        public GeefOndernemingVKBO GeefOndernemingVKBO;
        
        public GeefOndernemingVKBORequest()
        {
        }
        
        public GeefOndernemingVKBORequest(GeefOndernemingVKBO GeefOndernemingVKBO)
        {
            this.GeefOndernemingVKBO = GeefOndernemingVKBO;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [MessageContract(IsWrapped=false)]
    public partial class GeefOndernemingVKBOResponse1
    {
        
        [MessageBodyMember(Namespace="http://webservice.geefondernemingvkbodienst-02_00.onderneming-02_00.vip.vlaandere" +
                                     "n.be", Order=0)]
        public GeefOndernemingVKBOResponse GeefOndernemingVKBOResponse;
        
        public GeefOndernemingVKBOResponse1()
        {
        }
        
        public GeefOndernemingVKBOResponse1(GeefOndernemingVKBOResponse GeefOndernemingVKBOResponse)
        {
            this.GeefOndernemingVKBOResponse = GeefOndernemingVKBOResponse;
        }
    }
    
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface OndernemingGeefOndernemingVKBOPortTypeChannel : OndernemingGeefOndernemingVKBOPortType, IClientChannel
    {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OndernemingGeefOndernemingVKBOPortTypeClient : ClientBase<OndernemingGeefOndernemingVKBOPortType>, OndernemingGeefOndernemingVKBOPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);
        
        public OndernemingGeefOndernemingVKBOPortTypeClient() : 
                base(GetDefaultBinding(), GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Onderneming_GeefOndernemingVKBOHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OndernemingGeefOndernemingVKBOPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OndernemingGeefOndernemingVKBOPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OndernemingGeefOndernemingVKBOPortTypeClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) : 
                base(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OndernemingGeefOndernemingVKBOPortTypeClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Task<GeefOndernemingVKBOResponse1> GeefOndernemingVKBOAsync(GeefOndernemingVKBORequest request)
        {
            return base.Channel.GeefOndernemingVKBOAsync(request);
        }
        
        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual Task CloseAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
        }
        
        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Onderneming_GeefOndernemingVKBOHttpPort))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Onderneming_GeefOndernemingVKBOHttpPort))
            {
                return new EndpointAddress("https://magdaondernemingdienst.vlaanderen.be/GeefOndernemingVKBODienst-02.00/soap" +
                                           "/WebService");
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static Binding GetDefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.Onderneming_GeefOndernemingVKBOHttpPort);
        }
        
        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return GetEndpointAddress(EndpointConfiguration.Onderneming_GeefOndernemingVKBOHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            Onderneming_GeefOndernemingVKBOHttpPort,
        }
    }
}
