namespace AssociationRegistry.Acties.VerwerkWeigeringDubbelDoorAuthentiekeVereniging;

using Vereniging;

public record VerwerkWeigeringDubbelDoorAuthentiekeVerenigingCommand(VCode VCode, VCode VCodeAuthentiekeVereniging);
