namespace AssociationRegistry.CommandHandling.DecentraalBeheer.Acties.Vertegenwoordigers.VoegVertegenwoordigerToe;

using AssociationRegistry.DecentraalBeheer.Vereniging;

public record VoegVertegenwoordigerToeCommand(VCode VCode, IToeTeVoegenVertegenwoordiger Vertegenwoordiger);

