namespace AssociationRegistry.Acties.Vertegenwoordigers.VoegVertegenwoordigerToe;

using AssociationRegistry.Vereniging;

public record VoegVertegenwoordigerToeCommand(VCode VCode, Vertegenwoordiger Vertegenwoordiger);
