namespace AssociationRegistry.CommandHandling.DecentraalBeheer.Acties.Vertegenwoordigers.VerwijderVertegenwoordiger;

using AssociationRegistry.DecentraalBeheer.Vereniging;

public record VerwijderVertegenwoordigerCommand(VCode VCode, int VertegenwoordigerId);
