//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Repertorium.RegistreerUitschrijvingPortType", Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be", ConfigurationName="AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RepertoriumRegistre" +
        "erUitschrijvingPortType")]
    internal interface RepertoriumRegistreerUitschrijvingPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijvingResponse1> RegistreerUitschrijvingAsync(AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijvingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class RegistreerUitschrijving
    {
        
        private VerzoekType verzoekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public VerzoekType Verzoek
        {
            get
            {
                return this.verzoekField;
            }
            set
            {
                this.verzoekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class VerzoekType
    {
        
        private ContextType contextField;
        
        private VragenType vragenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ContextType Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public VragenType Vragen
        {
            get
            {
                return this.vragenField;
            }
            set
            {
                this.vragenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class ContextType
    {
        
        private string naamField;
        
        private string versieField;
        
        private BerichtType berichtField;
        
        private AnnotatieType[] annotatiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Versie
        {
            get
            {
                return this.versieField;
            }
            set
            {
                this.versieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BerichtType Bericht
        {
            get
            {
                return this.berichtField;
            }
            set
            {
                this.berichtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Annotatie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AnnotatieType[] Annotaties
        {
            get
            {
                return this.annotatiesField;
            }
            set
            {
                this.annotatiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class BerichtType
    {
        
        private BerichtTypeType typeField;
        
        private TijdstipType tijdstipField;
        
        private AfzenderAdresType afzenderField;
        
        private OntvangerAdresType ontvangerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BerichtTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public TijdstipType Tijdstip
        {
            get
            {
                return this.tijdstipField;
            }
            set
            {
                this.tijdstipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AfzenderAdresType Afzender
        {
            get
            {
                return this.afzenderField;
            }
            set
            {
                this.afzenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public OntvangerAdresType Ontvanger
        {
            get
            {
                return this.ontvangerField;
            }
            set
            {
                this.ontvangerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public enum BerichtTypeType
    {
        
        /// <remarks/>
        VRAAG,
        
        /// <remarks/>
        ANTWOORD,
        
        /// <remarks/>
        VOORLOPIG_ANTWOORD,
        
        /// <remarks/>
        DATAGRAM,
        
        /// <remarks/>
        BEVESTIGING,
        
        /// <remarks/>
        UITZONDERING,
        
        /// <remarks/>
        PUBLICATIE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class TijdstipType
    {
        
        private string datumField;
        
        private string tijdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Tijd
        {
            get
            {
                return this.tijdField;
            }
            set
            {
                this.tijdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class UitzonderingType
    {
        
        private string identificatieField;
        
        private string oorsprongField;
        
        private UitzonderingTypeType typeField;
        
        private TijdstipType tijdstipField;
        
        private string diagnoseField;
        
        private string omstandigheidField;
        
        private AnnotatieType[] annotatiesField;
        
        private string[] elementReferentiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Identificatie
        {
            get
            {
                return this.identificatieField;
            }
            set
            {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Oorsprong
        {
            get
            {
                return this.oorsprongField;
            }
            set
            {
                this.oorsprongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public UitzonderingTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public TijdstipType Tijdstip
        {
            get
            {
                return this.tijdstipField;
            }
            set
            {
                this.tijdstipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Diagnose
        {
            get
            {
                return this.diagnoseField;
            }
            set
            {
                this.diagnoseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Omstandigheid
        {
            get
            {
                return this.omstandigheidField;
            }
            set
            {
                this.omstandigheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Annotatie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AnnotatieType[] Annotaties
        {
            get
            {
                return this.annotatiesField;
            }
            set
            {
                this.annotatiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ElementReferentie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ElementReferenties
        {
            get
            {
                return this.elementReferentiesField;
            }
            set
            {
                this.elementReferentiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public enum UitzonderingTypeType
    {
        
        /// <remarks/>
        FOUT,
        
        /// <remarks/>
        WAARSCHUWING,
        
        /// <remarks/>
        INFORMATIE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class AnnotatieType
    {
        
        private string naamField;
        
        private string waardeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Waarde
        {
            get
            {
                return this.waardeField;
            }
            set
            {
                this.waardeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class ResultaatCodeType
    {
        
        private string beschrijvingField;
        
        private ResultaatEnumType valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Beschrijving
        {
            get
            {
                return this.beschrijvingField;
            }
            set
            {
                this.beschrijvingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ResultaatEnumType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public enum ResultaatEnumType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class AntwoordInhoudType
    {
        
        private ResultaatCodeType resultaatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultaatCodeType Resultaat
        {
            get
            {
                return this.resultaatField;
            }
            set
            {
                this.resultaatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class AntwoordType
    {
        
        private string referteField;
        
        private AntwoordInhoudType inhoudField;
        
        private UitzonderingType[] uitzonderingenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public AntwoordInhoudType Inhoud
        {
            get
            {
                return this.inhoudField;
            }
            set
            {
                this.inhoudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Uitzondering", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UitzonderingType[] Uitzonderingen
        {
            get
            {
                return this.uitzonderingenField;
            }
            set
            {
                this.uitzonderingenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class AntwoordenType
    {
        
        private AntwoordType antwoordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AntwoordType Antwoord
        {
            get
            {
                return this.antwoordField;
            }
            set
            {
                this.antwoordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class RepliekType
    {
        
        private ContextType contextField;
        
        private AntwoordenType antwoordenField;
        
        private UitzonderingType[] uitzonderingenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ContextType Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public AntwoordenType Antwoorden
        {
            get
            {
                return this.antwoordenField;
            }
            set
            {
                this.antwoordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Uitzondering", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UitzonderingType[] Uitzonderingen
        {
            get
            {
                return this.uitzonderingenField;
            }
            set
            {
                this.uitzonderingenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class PeriodeOptioneelType
    {
        
        private string beginField;
        
        private string eindeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Einde
        {
            get
            {
                return this.eindeField;
            }
            set
            {
                this.eindeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://repertorium-02_01.vip.vlaanderen.be")]
    public partial class SubjectType
    {
        
        private string rolField;
        
        private string typeField;
        
        private string sleutelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Sleutel
        {
            get
            {
                return this.sleutelField;
            }
            set
            {
                this.sleutelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://repertorium-02_01.vip.vlaanderen.be")]
    public partial class BetrokkenSubjectType
    {
        
        private string typeField;
        
        private SubjectType[] subjectenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Subject", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SubjectType[] Subjecten
        {
            get
            {
                return this.subjectenField;
            }
            set
            {
                this.subjectenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://repertorium-02_01.vip.vlaanderen.be")]
    public partial class UitschrijvingType
    {
        
        private string identificatieField;
        
        private string hoedanigheidField;
        
        private BetrokkenSubjectType betrokkenSubjectField;
        
        private PeriodeOptioneelType periodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Identificatie
        {
            get
            {
                return this.identificatieField;
            }
            set
            {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Hoedanigheid
        {
            get
            {
                return this.hoedanigheidField;
            }
            set
            {
                this.hoedanigheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BetrokkenSubjectType BetrokkenSubject
        {
            get
            {
                return this.betrokkenSubjectField;
            }
            set
            {
                this.betrokkenSubjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public PeriodeOptioneelType Periode
        {
            get
            {
                return this.periodeField;
            }
            set
            {
                this.periodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class VraagInhoudType
    {
        
        private UitschrijvingType uitschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UitschrijvingType Uitschrijving
        {
            get
            {
                return this.uitschrijvingField;
            }
            set
            {
                this.uitschrijvingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class VraagType
    {
        
        private string referteField;
        
        private VraagInhoudType inhoudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public VraagInhoudType Inhoud
        {
            get
            {
                return this.inhoudField;
            }
            set
            {
                this.inhoudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class VragenType
    {
        
        private VraagType vraagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public VraagType Vraag
        {
            get
            {
                return this.vraagField;
            }
            set
            {
                this.vraagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class OntvangerAdresType
    {
        
        private string identificatieField;
        
        private string naamField;
        
        private string referteField;
        
        private string organisatieEenheidField;
        
        private string hoedanigheidField;
        
        private string gebruikerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Identificatie
        {
            get
            {
                return this.identificatieField;
            }
            set
            {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OrganisatieEenheid
        {
            get
            {
                return this.organisatieEenheidField;
            }
            set
            {
                this.organisatieEenheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Hoedanigheid
        {
            get
            {
                return this.hoedanigheidField;
            }
            set
            {
                this.hoedanigheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Gebruiker
        {
            get
            {
                return this.gebruikerField;
            }
            set
            {
                this.gebruikerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generiek-02_00.vip.vlaanderen.be")]
    public partial class AfzenderAdresType
    {
        
        private string identificatieField;
        
        private string naamField;
        
        private string referteField;
        
        private string organisatieEenheidField;
        
        private string hoedanigheidField;
        
        private string gebruikerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Identificatie
        {
            get
            {
                return this.identificatieField;
            }
            set
            {
                this.identificatieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Referte
        {
            get
            {
                return this.referteField;
            }
            set
            {
                this.referteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OrganisatieEenheid
        {
            get
            {
                return this.organisatieEenheidField;
            }
            set
            {
                this.organisatieEenheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Hoedanigheid
        {
            get
            {
                return this.hoedanigheidField;
            }
            set
            {
                this.hoedanigheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Gebruiker
        {
            get
            {
                return this.gebruikerField;
            }
            set
            {
                this.gebruikerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
        "deren.be")]
    public partial class RegistreerUitschrijvingResponse
    {
        
        private RepliekType repliekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RepliekType Repliek
        {
            get
            {
                return this.repliekField;
            }
            set
            {
                this.repliekField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class RegistreerUitschrijvingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
            "deren.be", Order=0)]
        public AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijving RegistreerUitschrijving;
        
        public RegistreerUitschrijvingRequest()
        {
        }
        
        public RegistreerUitschrijvingRequest(AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijving RegistreerUitschrijving)
        {
            this.RegistreerUitschrijving = RegistreerUitschrijving;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class RegistreerUitschrijvingResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.registreeruitschrijvingdienst-02_01.repertorium-02_01.vip.vlaan" +
            "deren.be", Order=0)]
        public AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijvingResponse RegistreerUitschrijvingResponse;
        
        public RegistreerUitschrijvingResponse1()
        {
        }
        
        public RegistreerUitschrijvingResponse1(AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijvingResponse RegistreerUitschrijvingResponse)
        {
            this.RegistreerUitschrijvingResponse = RegistreerUitschrijvingResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface RepertoriumRegistreerUitschrijvingPortTypeChannel : AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RepertoriumRegistreerUitschrijvingPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class RepertoriumRegistreerUitschrijvingPortTypeClient : System.ServiceModel.ClientBase<AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RepertoriumRegistreerUitschrijvingPortType>, AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RepertoriumRegistreerUitschrijvingPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RepertoriumRegistreerUitschrijvingPortTypeClient() : 
                base(RepertoriumRegistreerUitschrijvingPortTypeClient.GetDefaultBinding(), RepertoriumRegistreerUitschrijvingPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Repertorium_RegistreerUitschrijvingHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RepertoriumRegistreerUitschrijvingPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(RepertoriumRegistreerUitschrijvingPortTypeClient.GetBindingForEndpoint(endpointConfiguration), RepertoriumRegistreerUitschrijvingPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RepertoriumRegistreerUitschrijvingPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RepertoriumRegistreerUitschrijvingPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RepertoriumRegistreerUitschrijvingPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RepertoriumRegistreerUitschrijvingPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RepertoriumRegistreerUitschrijvingPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijvingResponse1> RegistreerUitschrijvingAsync(AssociationRegistry.Integrations.Magda.Repertorium.RegistreerUitschrijving.RegistreerUitschrijvingRequest request)
        {
            return base.Channel.RegistreerUitschrijvingAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Repertorium_RegistreerUitschrijvingHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Repertorium_RegistreerUitschrijvingHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("https://magdarepertoriumdienst.vlaanderen.be/RegistreerUitschrijvingDienst-02.01/" +
                        "soap/WebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RepertoriumRegistreerUitschrijvingPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.Repertorium_RegistreerUitschrijvingHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RepertoriumRegistreerUitschrijvingPortTypeClient.GetEndpointAddress(EndpointConfiguration.Repertorium_RegistreerUitschrijvingHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            Repertorium_RegistreerUitschrijvingHttpPort,
        }
    }
}
