//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociationRegistry {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssociationRegistry.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string WebsiteMissingPeriod {
            get {
                return ResourceManager.GetString("WebsiteMissingPeriod", resourceCulture);
            }
        }
        
        public static string InvalidWebsiteStart {
            get {
                return ResourceManager.GetString("InvalidWebsiteStart", resourceCulture);
            }
        }
        
        public static string InvalidTelefoonNummerCharacter {
            get {
                return ResourceManager.GetString("InvalidTelefoonNummerCharacter", resourceCulture);
            }
        }
        
        public static string NoNumbersInTelefoonNummer {
            get {
                return ResourceManager.GetString("NoNumbersInTelefoonNummer", resourceCulture);
            }
        }
        
        public static string InvalidSocialMediaStart {
            get {
                return ResourceManager.GetString("InvalidSocialMediaStart", resourceCulture);
            }
        }
        
        public static string SocialMediaMissingPeriod {
            get {
                return ResourceManager.GetString("SocialMediaMissingPeriod", resourceCulture);
            }
        }
        
        public static string InvalidContactType {
            get {
                return ResourceManager.GetString("InvalidContactType", resourceCulture);
            }
        }
        
        public static string DoelgroepOutOfRange {
            get {
                return ResourceManager.GetString("DoelgroepOutOfRange", resourceCulture);
            }
        }
        
        public static string InvalidDoelgroepRange {
            get {
                return ResourceManager.GetString("InvalidDoelgroepRange", resourceCulture);
            }
        }
        
        public static string AfdelingCanNotBeUnsubscribedFromPubliekeDatastroom {
            get {
                return ResourceManager.GetString("AfdelingCanNotBeUnsubscribedFromPubliekeDatastroom", resourceCulture);
            }
        }
        
        public static string GeenGeldigeVerenigingInKbo {
            get {
                return ResourceManager.GetString("GeenGeldigeVerenigingInKbo", resourceCulture);
            }
        }
        
        public static string UnsupportedOperationForVerenigingstype {
            get {
                return ResourceManager.GetString("UnsupportedOperationForVerenigingstype", resourceCulture);
            }
        }
        
        public static string DuplicateHoofdactiviteit {
            get {
                return ResourceManager.GetString("DuplicateHoofdactiviteit", resourceCulture);
            }
        }
        
        public static string InvalidInszChars {
            get {
                return ResourceManager.GetString("InvalidInszChars", resourceCulture);
            }
        }
        
        public static string InvalidInszLength {
            get {
                return ResourceManager.GetString("InvalidInszLength", resourceCulture);
            }
        }
        
        public static string InvalidInszMod97 {
            get {
                return ResourceManager.GetString("InvalidInszMod97", resourceCulture);
            }
        }
        
        public static string InvalidKboNummerChars {
            get {
                return ResourceManager.GetString("InvalidKboNummerChars", resourceCulture);
            }
        }
        
        public static string InvalidKboNummerLength {
            get {
                return ResourceManager.GetString("InvalidKboNummerLength", resourceCulture);
            }
        }
        
        public static string InvalidKboNummerMod97 {
            get {
                return ResourceManager.GetString("InvalidKboNummerMod97", resourceCulture);
            }
        }
        
        public static string DuplicateLocatie {
            get {
                return ResourceManager.GetString("DuplicateLocatie", resourceCulture);
            }
        }
        
        public static string IncompleteAdres {
            get {
                return ResourceManager.GetString("IncompleteAdres", resourceCulture);
            }
        }
        
        public static string IncompleteAdresId {
            get {
                return ResourceManager.GetString("IncompleteAdresId", resourceCulture);
            }
        }
        
        public static string InvalidBroncode {
            get {
                return ResourceManager.GetString("InvalidBroncode", resourceCulture);
            }
        }
        
        public static string InvalidBronwaardeForAR {
            get {
                return ResourceManager.GetString("InvalidBronwaardeForAR", resourceCulture);
            }
        }
        
        public static string MissingAdres {
            get {
                return ResourceManager.GetString("MissingAdres", resourceCulture);
            }
        }
        
        public static string MultipleCorrespondentieLocaties {
            get {
                return ResourceManager.GetString("MultipleCorrespondentieLocaties", resourceCulture);
            }
        }
        
        public static string MultiplePrimaireLocaties {
            get {
                return ResourceManager.GetString("MultiplePrimaireLocaties", resourceCulture);
            }
        }
        
        public static string StardatumIsInFuture {
            get {
                return ResourceManager.GetString("StardatumIsInFuture", resourceCulture);
            }
        }
        
        public static string InvalidVCodeFormat {
            get {
                return ResourceManager.GetString("InvalidVCodeFormat", resourceCulture);
            }
        }
        
        public static string OutOfRangeVCode {
            get {
                return ResourceManager.GetString("OutOfRangeVCode", resourceCulture);
            }
        }
        
        public static string EmptyVerenigingsNaam {
            get {
                return ResourceManager.GetString("EmptyVerenigingsNaam", resourceCulture);
            }
        }
        
        public static string AchternaamBevatNummers {
            get {
                return ResourceManager.GetString("AchternaamBevatNummers", resourceCulture);
            }
        }
        
        public static string AchternaamZonderLetters {
            get {
                return ResourceManager.GetString("AchternaamZonderLetters", resourceCulture);
            }
        }
        
        public static string DuplicateInszProvided {
            get {
                return ResourceManager.GetString("DuplicateInszProvided", resourceCulture);
            }
        }
        
        public static string MultiplePrimaireVertegenwoordigers {
            get {
                return ResourceManager.GetString("MultiplePrimaireVertegenwoordigers", resourceCulture);
            }
        }
        
        public static string UnknownInsz {
            get {
                return ResourceManager.GetString("UnknownInsz", resourceCulture);
            }
        }
        
        public static string VoornaamBevatNummers {
            get {
                return ResourceManager.GetString("VoornaamBevatNummers", resourceCulture);
            }
        }
        
        public static string VoornaamZonderLetters {
            get {
                return ResourceManager.GetString("VoornaamZonderLetters", resourceCulture);
            }
        }
        
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        public static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        public static string CouldNotParseRequestException {
            get {
                return ResourceManager.GetString("CouldNotParseRequestException", resourceCulture);
            }
        }
        
        public static string InvalidBevestigingstokenProvided {
            get {
                return ResourceManager.GetString("InvalidBevestigingstokenProvided", resourceCulture);
            }
        }
    }
}
