<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://webservice.geefondernemingdienst-02_00.onderneming-02_00.vip.vlaanderen.be"
                  xmlns="http://webservice.geefondernemingdienst-02_00.onderneming-02_00.vip.vlaanderen.be"                  
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<wsdl:types>
		<xsd:schema targetNamespace="http://webservice.geefondernemingdienst-02_00.onderneming-02_00.vip.vlaanderen.be"
		            xmlns="http://webservice.geefondernemingdienst-02_00.onderneming-02_00.vip.vlaanderen.be"
		            xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		            elementFormDefault="unqualified" 
		            attributeFormDefault="unqualified"
		            version="2.00">
		            
			<xsd:include schemaLocation="GeefOnderneming.xsd"/>
			<xsd:include schemaLocation="GeefOndernemingResponse.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="GeefOndernemingRequest">
		<wsdl:part name="Verzoek" element="GeefOnderneming"/>
	</wsdl:message>
	<wsdl:message name="GeefOndernemingResponse">
		<wsdl:part name="Repliek" element="GeefOndernemingResponse"/>
	</wsdl:message>
	
	<wsdl:portType name="Onderneming.GeefOndernemingPortType">
		<wsdl:operation name="GeefOnderneming">
			<wsdl:input name="GeefOndernemingRequest" message="GeefOndernemingRequest"/>
			<wsdl:output name="GeefOndernemingResponse" message="GeefOndernemingResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="Onderneming.GeefOndernemingHttpBinding" type="Onderneming.GeefOndernemingPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GeefOnderneming">
			<soap:operation soapAction="http://magdaondernemingdienst-intern-aip.vonet.be/GeefOndernemingDienst-02.00/soap/WebService"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="Onderneming.GeefOnderneming">
		<wsdl:port name="Onderneming.GeefOndernemingHttpPort" binding="Onderneming.GeefOndernemingHttpBinding">
			<soap:address location="https://magdaondernemingdienst.vlaanderen.be/GeefOndernemingDienst-02.00/soap/WebService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
