namespace AssociationRegistry.CommandHandling.DecentraalBeheer.Acties.Dubbelbeheer.Reacties.AanvaardCorrectieDubbel;

using AssociationRegistry.DecentraalBeheer.Vereniging;

public record AanvaardCorrectieDubbeleVerenigingCommand(VCode VCode, VCode VCodeDubbeleVereniging);
