namespace AssociationRegistry.CommandHandling.DecentraalBeheer.Acties.Dubbelbeheer.Commands.CorrigeerMarkeringAlsDubbelVan;

using AssociationRegistry.DecentraalBeheer.Vereniging;

public record CorrigeerMarkeringAlsDubbelVanCommand(VCode VCode);
