name: Manual Lambda deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (format: x.xxx.x, ie: 1.221.1)'
        required: true
      environment:
        description: 'Select the environment to deploy to'
        required: true
        type: choice
        options:
          - test_ik4
          - staging_ik4
          - production_ik4

jobs:
  deployment:
    name: Deploy lambdas
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            'kbosync',
          ]
    steps:
      - name: Set env
        id: set_env
        run: |
          if [[ "${{ inputs.environment }}" == "test_ik4" ]]; then
            echo "ENV=test" >> $GITHUB_ENV
          elif [[ "${{ inputs.environment }}" == "staging_ik4" ]]; then
            echo "ENV=stg" >> $GITHUB_ENV
          elif [[ "${{ inputs.environment }}" == "production_ik4" ]]; then
            echo "ENV=prd" >> $GITHUB_ENV
          fi
      - name: CD
        id: awscurl-polling-action
        env:
          BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/kbosync/${{ env.ENV }}/deploy/v4
          STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/kbosync/${{ env.ENV }}/deploy/v4/status
        uses: informatievlaanderen/awscurl-polling-action/polling-action@deploy-v4
        with:
          environment: ${{ env.ENV }}
          version: ${{ github.event.inputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID_IK4 }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY_IK4 }}
          deploy-target: 'lambda'
          domain: 'verenigingsregister'
          project: 'verenigingsregister'
          application: 'lambda'
          interval: 2
      - name: output
        shell: bash
        if: always()
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}