name: Main

on:
  push:
  workflow_dispatch:

concurrency: CI
jobs:

  pack-association-registry:
    name: Pack Association Registry Domain
    uses: Informatievlaanderen/build-pipeline/.github/workflows/pack.yml@main
    needs: [ set-release-version ]
    if: ${{ (github.repository_owner == 'Informatievlaanderen') && (needs.set-release-version.outputs.version != 'none') }}
    with:
      pack-file: Be.Vlaanderen.Basisregisters.AssociationRegistry
      build-project: AssociationRegistry
      dotnet-version: ${{ secrets.VBR_DOTNET_VERSION }}
      semver: ${{ needs.set-release-version.outputs.version }}
    secrets: inherit

  pack-association-registry-magda:
    name: Pack Association Registry Magda
    uses: Informatievlaanderen/build-pipeline/.github/workflows/pack.yml@main
    needs: [ set-release-version ]
    if: ${{ (github.repository_owner == 'Informatievlaanderen') && (needs.set-release-version.outputs.version != 'none') }}
    with:
      pack-file: Be.Vlaanderen.Basisregisters.AssociationRegistry.Magda
      build-project: AssociationRegistry.Magda
      dotnet-version: ${{ secrets.VBR_DOTNET_VERSION }}
      semver: ${{ needs.set-release-version.outputs.version }}
    secrets: inherit

  publish_to_nuget:
    needs: [ release ]
    if: ${{ (github.repository_owner == 'Informatievlaanderen') && (needs.release.outputs.version != 'none') }}
    name: Publish to NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ secrets.VBR_DOTNET_VERSION }}

      - name: .NET version
        shell: bash
        run: dotnet --info

      - name: Download NuGet package 'association-registry'
        uses: actions/download-artifact@v4.1.4
        with:
          name: nuget-Be.Vlaanderen.Basisregisters.AssociationRegistry-${{ needs.release.outputs.version }}
          path: dist/nuget/Be.Vlaanderen.Basisregisters.AssociationRegistry.${{ needs.release.outputs.version }}.nupkg

      - name: Publish packages to NuGet 'association-registry'
        shell: bash
        run: |
          dotnet nuget push dist/nuget/Be.Vlaanderen.Basisregisters.AssociationRegistry.$SEMVER.nupkg --source nuget.org --api-key $NUGET_API_KEY
        env:
          SEMVER: ${{  needs.release.outputs.version }}
          WORKSPACE: ${{ github.workspace }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Download NuGet package 'association-registry-magda'
        uses: actions/download-artifact@v4.1.4
        with:
          name: nuget-Be.Vlaanderen.Basisregisters.AssociationRegistry.Magda-${{ needs.release.outputs.version }}
          path: dist/nuget/Be.Vlaanderen.Basisregisters.AssociationRegistry.Magda.${{ needs.release.outputs.version }}.nupkg

      - name: Publish packages to NuGet 'association-registry-magda'
        shell: bash
        run: |
          dotnet nuget push dist/nuget/Be.Vlaanderen.Basisregisters.AssociationRegistry.$SEMVER.nupkg --source nuget.org --api-key $NUGET_API_KEY
        env:
          SEMVER: ${{  needs.release.outputs.version }}
          WORKSPACE: ${{ github.workspace }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
