name: "[POSTMAN] Full Regression Suite"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'
    - cron: '0 2 * * 3'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "34061079-b9019512-c4b9-4844-9e86-e70fc8d65a4a" -e "24467383-b7b1ecfe-ae6d-4ded-a378-db554a2bc155" \
            -r html,json \
            --reporter-html-export test-report-full.html \
            --reporter-json-export test-results.json

          failed_request_ids = set()
          
          failures = soup.find(id="failures-and-errors-list")
          if failures:
              for node in failures.find_all(attrs={"data-accordion-request-id": True}):
                  failed_request_ids.add(
                      node["data-accordion-request-id"]
                  )
          
          print(f"Failed requests: {len(failed_request_ids)}")
          
          removed = 0
          
          # verwijder alle request-details die niet gefaald hebben
          for node in soup.find_all(attrs={"data-accordion-request-id": True}):
          
              # failure-overzicht zelf laten staan
              if node.find_parent(id="failures-and-errors-list"):
                  continue
          
              req_id = node.get("data-accordion-request-id")
          
              if req_id not in failed_request_ids:
                  node.decompose()
                  removed += 1
          
          print(f"Removed {removed} successful requests")

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-reports
          path: |
            test-report-full.html
            test-report-only-failure-detail.html
            test-results.json
            postman-cli-reports/
          retention-days: 30

      - name: Notify Slack
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JOB_STATUS: ${{ job.status }}
        run: |
          if [ "$JOB_STATUS" = "success" ]; then
            MESSAGE="✅ *API tests succeeded* on \`${{ github.workflow }}\` in repo \`${{ github.repository }}\`.\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
          else
            MESSAGE="❌ *API tests failed* on \`${{ github.workflow }}\` in repo \`${{ github.repository }}\`.\n<@U03P611N5TK>,<@koenmetsu> please check the logs: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$MESSAGE\"}" \
          $SLACK_WEBHOOK_URL
