name: "[Sigrid] Publish"

on:
  push:
    branches: [ main ]

jobs:
  sigridci:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Sigrid CI Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@main
        with:
          customer: digitaalvlaanderen
          system: association-registry
          publishonly: true
        env:
          SIGRID_CI_TOKEN: ${{ secrets.SIGRID_CI_TOKEN }}
